### ISSUE TITLE
# Error: 'PySide2.QtWidgets.QShortcut' called with wrong argument types:

### ISSUE THREAD

**Issue by tccoleman** [theRussetPotato/weights_editor#1]
Windows 10
Maya 2020.4

Ran the Drag 'n Drop Installer and ran the command:

from weights_editor_tool import weights_editor
weights_editor.run()
```
# Error: 'PySide2.QtWidgets.QShortcut' called with wrong argument types:
#   PySide2.QtWidgets.QShortcut(long, QWidget)
# Supported signatures:
#   PySide2.QtWidgets.QShortcut(PySide2.QtGui.QKeySequence, PySide2.QtWidgets.QWidget, Callable, PySide2.QtCore.Qt.ShortcutContext=PySide2.QtCore.Qt.ShortcutContext.WindowShortcut)
#   PySide2.QtWidgets.QShortcut(PySide2.QtGui.QKeySequence, PySide2.QtWidgets.QWidget, str=None, str=None, PySide2.QtCore.Qt.ShortcutContext=PySide2.QtCore.Qt.ShortcutContext.WindowShortcut)
#   PySide2.QtWidgets.QShortcut(PySide2.QtWidgets.QWidget)
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:/Users/colem/OneDrive/Documents/maya/scripts\weights_editor_tool\weights_editor.py", line 1799, in run
#     WeightsEditor.run()
#   File "C:/Users/colem/OneDrive/Documents/maya/scripts\weights_editor_tool\weights_editor.py", line 116, in run
#     inst = cls()
#   File "C:/Users/colem/OneDrive/Documents/maya/scripts\weights_editor_tool\weights_editor.py", line 111, in __init__
#     self.register_shortcuts()
#   File "C:/Users/colem/OneDrive/Documents/maya/scripts\weights_editor_tool\weights_editor.py", line 689, in register_shortcuts
#     hotkey.key_code(), hotkey.func))
#   File "C:/Users/colem/OneDrive/Documents/maya/scripts\weights_editor_tool\weights_editor_utils.py", line 35, in create_shortcut
#     shortcut = QtWidgets.QShortcut(key_sequence, get_maya_window())
# TypeError: 'PySide2.QtWidgets.QShortcut' called with wrong argument types:
#   PySide2.QtWidgets.QShortcut(long, QWidget)
# Supported signatures:
#   PySide2.QtWidgets.QShortcut(PySide2.QtGui.QKeySequence, PySide2.QtWidgets.QWidget, Callable, PySide2.QtCore.Qt.ShortcutContext=PySide2.QtCore.Qt.ShortcutContext.WindowShortcut)
#   PySide2.QtWidgets.QShortcut(PySide2.QtGui.QKeySequence, PySide2.QtWidgets.QWidget, str=None, str=None, PySide2.QtCore.Qt.ShortcutContext=PySide2.QtCore.Qt.ShortcutContext.WindowShortcut)
#   PySide2.QtWidgets.QShortcut(PySide2.QtWidgets.QWidget) #
```

**Comment by theRussetPotato** [comment]
That's weird, since I just tested with a fresh install of Maya 2020 with no issues.
I did update the tool to see if that would fix it, so you can try the latest release.
Thanks for reporting this in.

**Comment by tccoleman** [comment]
Your fix worked, thanks for your quick response and this useful skin weighting tool.  Look forward to using it.  Tim

**Comment by theRussetPotato** [comment]
Glad to hear it's working on your end!
